name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip3 install -r requirements.txt
        pip3 install flake8  # Install flake8 for linting

    - name: Check for syntax errors
      run: |
        python3 -m py_compile $(find . -name "*.py")

    - name: Run flake8
      run: |
        flake8 .

    - name: Test invalid code
      run: |
        echo "def invalid_function():" > invalid_code.py
        echo "    return" >> invalid_code.py
        echo "invalid_function(" >> invalid_code.py  # Missing closing parenthesis
        python3 -m py_compile invalid_code.py

    - name: Run pytest
      run: |
        pytest